export const HANDLE_USER_ON_CLICK = "HANDLE_USER_ON_CLICK";
export const HANDLE_ROLES_ON_CLICK = "HANDLE_ROLES_ON_CLICK";
export const HANDLE_ACTIONS_ON_CLICK = "HANDLE_ACTIONS_ON_CLICK";
export const HANDLE_ROLE_ACTION_ON_CLICK = "HANDLE_ROLE_ACTION_ON_CLICK";

export const ON_CLICK_LOGIN = "ON_CLICK_LOGIN";
export const ON_CLICK_LOGOUT ="ON_CLICK_LOGOUT";

export const ON_CLICK_CREATE_ROLE = "ON_CLICK_CREATE_ROLE";
export const ON_CLICK_UPDATE_ROLE = "ON_CLICK_UPDATE_ROLE";
export const ON_CLICK_DELETE_ROLE = "ON_CLICK_DELETE_ROLE";

export const ON_CLICK_CREATE_ACTION = "ON_CLICK_CREATE_ACTION";
export const ON_CLICK_UPDATE_ACTION = "ON_CLICK_UPDATE_ACTION";
export const ON_CLICK_DELETE_ACTION = "ON_CLICK_DELETE_ACTION";

export const HANDLE_FIELD_CHANGE = "HANDLE_FIELD_CHANGE";
export const HANDLE_CLOSE = "HANDLE_CLOSE";

export const HANDLE_DRAWER_OPEN = "HANDLE_DRAWER_OPEN";
export const HANDLE_DRAWER_CLOSE = "HANDLE_DRAWER_CLOSE";

export const TOGGLE_DIALOG = "TOGGLE_DIALOG";



export const MAP_ACTION_ROLE = "MAP_ACTION_ROLE";
export const HANDLE_CREATE_USER_ROLE = "HANDLE_CREATE_USER_ROLE";


export const ON_CLICK_UPDATE_USER_ROLE="ON_CLICK_UPDATE_USER_ROLE";
